name: Automated Pull Request Comment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Comment on Pull Request
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for your contribution. Please consider the following:
            - Did you add an explanation about what your changes do?
            - Did you make tests for your changes?
            - Did you update documentation accordingly?
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
